### ISSUE TITLE
it dont worky

### ISSUE THREAD

**Issue by Unnamed010** [KillzXGaming/MK8-Parts-Bin-Converter#1]
after extracting and reinjecting, even when not making any changes to any of the jsons the new parts.bin does some weird shit to the collision of the vehicles which makes the game basically unplayable example: https://i.imgur.com/XUy6Xx5.png

**Comment by KillzXGaming** [comment]
Fixed https://github.com/KillzXGaming/MK8-Parts-Bin-Converter/commit/446d4a2b5c1bd569b872c04f2db73a19c509b83e
